var Resume={};
(function(){var m=Array.prototype.slice;this.partial=function(d){var a=m.call(arguments,1);return function(){d.apply(this,a.concat(m.call(arguments)))}};this.sync=function(d,a,b){var c=false,f=false,e;e=function(){c&&f&&b&&b()};d(function(){c=true;e()});a(function(){f=true;e()})};this.Ajax={get:function(d,a){var b=new XMLHttpRequest,c=function(){var f=b.getResponseHeader("Content-Type");if(f=="application/json")return JSON.parse(b.responseText);if(f=="text/xml")return b.responseXML;return b.responseText};
b.onreadystatechange=function(){b.readyState==4&&a&&a(c())};b.open("GET",d,true);b.send()}};this.CanvasEffects={fadeIn:function(d,a){var b=this.x,c=this.y,f=a||this.getImageData(),e=this.context,h=1,n=f.height,k=f.width,g=f.data,i,p=g.length;i=setInterval(function(){for(var o=0.0625*h,j=e.createImageData(k,n),l=p,q=j.data;--l;)q[l]=(l+1)%4?g[l]:o*g[l];e.clearRect(b,c,k,n);e.putImageData(j,b,c);h++;if(h>16){clearInterval(i);d&&d()}},30)},fadeOut:function(d){var a=this.x,b=this.y,c=this.context.getImageData(a,
b,this.width,this.height),f=this.context,e=1,h=c.height,n=c.width,k=c.data,g,i=k.length;g=setInterval(function(){for(var p=1-e*0.0625,o=f.createImageData(n,h),j=i,l=o.data;--j;)l[j]=(j+1)%4?k[j]:p*k[j];f.clearRect(a,b,n,h);f.putImageData(o,a,b);e++;if(e>16){clearInterval(g);d&&d()}},30)},blurOut:function(d){var a=this.x,b=this.y,c=this.context.getImageData(a,b,this.width,this.height),f=16,e=this.context,h=this.height,n=this.width,k,g=c.data,i=g.length,p=i-5,o=n*4;k=setInterval(function(){for(var j=
1-1/f,l=i,q;--l;){q=g[l];if(l<p&&l>4&&l>o&&l+o<p)q=(q+g[l+4]+g[l-4]+g[l-o]+g[l+o])*0.2;g[l]=(l+1)%4?q:q*j}e.clearRect(a,b,n,h);e.putImageData(c,a,b);f--;if(f<=0){clearInterval(k);d&&d()}},30)}};var t;if(t=navigator.userAgent.match(/firefox\/(\d*)\.(\d*)\.(\d*)/i))if(t[1]<=3)this.CanvasEffects.blurOut=this.CanvasEffects.fadeOut}).call(Resume);
(function(){this.createBackground=function(m){var t={},d=document.documentElement.clientWidth,a=document.documentElement.clientHeight,b=m.canvas,c,f;t.canvas=b;b.width=d;b.height=a;t.context=c=b.getContext("2d");t.draw=function(){f=c.createRadialGradient(d/2,100,0,d/2,a/2,a);f.addColorStop(1,"#aaaaaa");f.addColorStop(0.1,"rgba(255,255,255,255)");c.fillStyle=f;c.fillRect(0,0,d,a)};window.addEventListener("resize",function(){b.width=d=document.documentElement.clientWidth;b.height=a=document.documentElement.clientHeight;
t.draw()},false);return t}}).call(Resume);
(function(){var m=function(a,b,c,f,e){var h=e/2,n=Math.PI/2,k=3*Math.PI/2;a.beginPath();a.arc(b+h,c+h,h,n,k,false);a.arc(b+f-h,c+e-h,h,k,n,false);a.closePath()},t=function(a){var b=a.text.replace(/\s/,"     "),c=a.context,f,e;a.width=a.context.measureText(b).width+40;a.height=32;a.getImageData=function(){if(f)return f;c.save();c.textAlign="center";c.textBaseline="alphabetic";c.font="12px Bebas";c.fillStyle="rgba(46, 52, 54, 0.75)";c.fillText(b,a.width/2,21);f=c.getImageData(0,0,a.width,a.height);
c.clearRect(0,0,a.width,a.height);c.restore();return f};a.getImageDataSelected=function(){if(e)return e;c.save();m(c,2.5,2.5,a.width-5,a.height-5);c.strokeStyle="#2e3436";c.lineWidth=5;c.stroke();e=c.getImageData(0,0,a.width,a.height);c.clearRect(0,0,a.width,a.height);c.restore();return e}},d=function(a){var b=a.context,c,f;a.height=25;a.width=150;a.padding=10;a.radius=a.height/2;var e=a.padding+a.height,h=a.padding+a.width,n=function(){var g=b.createLinearGradient(0,a.padding/2,0,a.height);g.addColorStop(0,
"#47595f");g.addColorStop(1,"#2e3436");return g}(),k=function(){var g=b.createLinearGradient(0,a.padding/2,0,a.height);g.addColorStop(0,"#fff");g.addColorStop(1,"#666");return g}();a.getImageData=function(){if(c)return c;b.save();b.textAlign="center";b.textBaseline="alphabetic";b.font="bold 12px Verdana";m(b,a.padding/2,a.padding/2,a.width,a.height);b.fillStyle="rgba(46, 52, 54, 0.9)";b.fill();b.fillStyle="#ccc";b.fillText(a.text,h/2,21);c=b.getImageData(0,0,h,e);b.clearRect(0,0,h,e);b.restore();
return c};a.getImageDataSelected=function(){if(f)return f;b.save();b.textAlign="center";b.textBaseline="alphabetic";b.font="bold 12px Verdana";m(b,a.padding/2,a.padding/2,a.width,a.height);b.fillStyle=n;b.fill();b.strokeStyle=k;b.lineWidth=2;b.stroke();b.fillStyle="#fff";b.fillText(a.text,h/2,21);f=b.getImageData(0,0,h,e);b.clearRect(0,0,h,e);b.restore();return f}};this.createButton=function(a){var b={};b.context=a.canvas.getContext("2d");b.x=a.x||0;b.y=a.y||0;b.text=a.text||"Button";b.handler=a.handler;
a.theme=="main"?d(b):t(b);return b}}).call(Resume);
(function(){var m=this,t=function(d){var a={},b=document.documentElement.clientWidth,c=document.documentElement.clientHeight,f,e,h=d.canvas,n,k=d.menu,g,i,p,o,j;h.width=b;h.height=c;a.canvas=h;a.context=n=h.getContext("2d");a.targetWidth=d.targetWidth||0;a.targetHeight=d.targetHeight||0;j=function(){a.x=Math.floor(b/2-f.width/2);a.y=Math.floor(c/2-f.height/2);a.width=f.width;a.height=f.height;a.targetX=d.targetX+a.x;a.targetY=d.targetY+a.y;p=a.targetX+a.targetWidth/2;o=a.targetY+a.targetHeight/2};
a.getImageData=function(l){if(e){l&&l();return e}if(d.image){f=new Image;f.addEventListener("load",function(){j();n.drawImage(f,a.x,a.y,a.width,a.height);e=n.getImageData(a.x,a.y,a.width,a.height);n.clearRect(a.x,a.y,a.width,a.height);l&&l()},false);f.src=d.image}};a.fadeIn=function(l){a.getImageData(function(){m.CanvasEffects.fadeIn.call(a,l)})};g=k.items[0];i=1/(g.height+g.padding);a.getSelected=function(l,q){if(p<l||p>l+k.width||o<q||o>q+k.height)return null;return k.items[Math.floor((o-q)*i)]};
window.addEventListener("resize",function(){b=document.documentElement.clientWidth;c=document.documentElement.clientHeight;j();if(m.currentPage===m.mainPage){h.width=b;h.height=c;n.putImageData(e,a.x=Math.floor(b/2-a.width/2),a.y=Math.floor(c/2-a.height/2))}},false);return a};this.createMainMenu=function(d){var a={},b=0,c=0,f=document.documentElement.clientWidth,e=document.documentElement.clientHeight,h=d.canvas,n,k=[],g,i,p,o,j,l,q,s;j=h.offsetLeft;l=h.offsetTop;h.width=f;h.height=e;a.canvas=h;a.x=
0;a.y=0;a.context=n=h.getContext("2d");for(p=0;i=d.items[p];p++){i.canvas=h;i.theme=i.theme||"main";i=m.createButton(i);b=b>i.width?b:i.width+i.padding;c+=i.height+i.padding;i.y=i.height*p+p*i.padding;k.push(i);i.getImageData()}a.items=k;a.width=b;a.height=c;d.itemTarget.menu=a;a.itemTarget=g=t(d.itemTarget);q=function(r){var u=r.clientX-j;r=r.clientY-l;var v,w;u=u+b>f?f-b:u;r=r+c>e?e-c:r;if(o=g.getSelected(u,r)){r=o.padding/2;u=g.targetX-r;r=g.targetY-o.y-r}n.clearRect(a.x,a.y,b,c);for(w=0;v=k[w];w++)n.putImageData(v===
o?v.getImageDataSelected():v.getImageData(),u,r+v.y);a.x=u;a.y=r};s=function(){if(o&&o.handler){o.handler(a);o=null}};a.fadeIn=function(r){document.body.style.cursor="url(img/blank.png), none";window.addEventListener("mousemove",q,false);window.addEventListener("click",s,false);g.fadeIn(function(){r&&r()})};a.fadeOut=function(r){var u=m.CanvasEffects.blurOut;document.body.style.cursor="auto";window.removeEventListener("mousemove",q,false);window.removeEventListener("click",s,false);u.call(a,function(){u.call(g,
r)})};window.addEventListener("resize",function(){f=document.documentElement.clientWidth;e=document.documentElement.clientHeight;if(m.currentPage===m.mainPage){h.width=f;h.height=e}},false);return a}}).call(Resume);
(function(){var m=this,t=function(d){var a={},b,c,f,e=d.canvas,h,n=true,k=false,g=false,i,p,o;e.width=document.documentElement.clientWidth;e.height=document.documentElement.clientHeight;a.canvas=e;a.context=h=e.getContext("2d");a.menu=c=d.menu;f=c.items;a.disableClick=function(){g=true};a.enableClick=function(){g=false};a.fadeIn=function(j){var l=m.currentPage.title,q;for(q=0;b=f[q];q++)if(b.text===l)break;a.current=b;a.index=q;a.x=b.x;a.y=b.y;a.width=b.width;a.height=b.height;m.CanvasEffects.fadeIn.call(a,
function(){window.addEventListener("click",o,false);window.addEventListener("mousemove",p,false);n=false;j&&j()},b.getImageDataSelected())};a.fadeOut=function(j){window.removeEventListener("click",o,false);window.removeEventListener("mousemove",p,false);n=true;m.CanvasEffects.fadeOut.call(a,j)};p=function(j){if(j=a.getItemAt(j.clientX,j.clientY)){document.body.style.cursor="pointer";if(j!==i){i=j;a.move(function(){k=false});k=true}}else{document.body.style.cursor="auto";i=a.current;a.move(function(){k=
false});k=true}};a.move=function(j){if(!k){var l,q=a.context,s=a.x,r=a.y;l=setInterval(function(){var u=i.x;if(u===s||n){clearInterval(l);j&&j()}else{q.clearRect(s,r,a.width,a.height);if(Math.abs(s-u)<10)s=u;else s+=u>s?10:-10;q.putImageData(i.getImageDataSelected(),s,r);a.x=s;a.y=r;a.width=i.width;a.height=i.height}},10)}};o=function(j){if(!g){j=a.getItemAt(j.clientX,j.clientY);if(!(!j||j===a.current))if(j.handler()!==false)a.current=j}};a.getItemAt=function(j,l){var q=0;q=c.menuX;var s=c.menuY;
j+=window.pageXOffset;l+=window.pageYOffset;if(l<s||l>s+c.menuHeight||j<q||j>q+c.menuWidth)return null;for(q=0;s=f[q];q++)if(j>=s.x&&j<s.x+s.width)return s;return null};window.addEventListener("resize",function(){if(m.currentPage===m.subPage){e.width=document.documentElement.clientWidth;e.height=document.documentElement.clientHeight;a.x=a.current.x;a.y=a.current.y;h.putImageData(a.current.getImageDataSelected(),a.x,a.y)}},false);return a};this.createSubMenu=function(d){var a={},b=d.canvas,c=document.documentElement.clientWidth,
f=document.documentElement.clientHeight,e,h=[],n,k,g,i=d.txtCurrentFillStyle||"#2e3436",p;b.width=c;b.height=f;a.canvas=b;a.current=d.current;a.context=e=b.getContext("2d");a.width=d.width||800;a.height=d.height||50;a.padding=10;a.x=d.x||Math.floor(c/2-a.width/2-a.padding);a.y=d.y||Math.floor(25-a.padding);a.menuY=a.y+a.padding;for(k=0;n=d.items[k];k++){n.canvas=b;n=m.createButton(n);n.getImageDataSelected();h.push(n)}a.items=h;a.getImageData=function(){var o,j,l;if(p)return p;e.save();e.font="22pt Bebas";
e.textAlign="start";e.textBaseline="alphabetic";e.fillStyle=i;o=e.measureText(m.title).width+15;l=a.padding+a.x+o;a.menuX=l;for(o=0;j=h[o];o++){j.x=l;j.y=a.menuY;e.putImageData(j.getImageData(),l,j.y);l+=j.width}a.menuWidth=l;a.menuHeight=h[0].height;e.fillText(m.title,a.x+a.padding/2,54);p=e.getImageData(a.x,a.y,a.width+a.padding*2,a.height+a.padding*2);e.clearRect(a.x,a.y,a.width+a.padding*2,a.height+a.padding*2);e.restore();return p};a.itemSelector=g=t({menu:a,canvas:d.itemSelector.canvas});a.fadeIn=
function(o){m.CanvasEffects.fadeIn.call(a,function(){g.fadeIn(o)})};a.fadeOut=function(o){g.fadeOut(function(){m.CanvasEffects.blurOut.call(a,o)})};window.addEventListener("resize",function(){c=document.documentElement.clientWidth;f=document.documentElement.clientHeight;a.x=d.x||Math.floor(c/2-a.width/2-a.padding);a.y=d.y||Math.floor(25-a.padding);p=null;if(m.currentPage===m.subPage){b.width=c;b.height=f;e.putImageData(a.getImageData(),a.x,a.y)}},false);return a}}).call(Resume);
(function(){var m=this;this.createMainPage=function(t){if(m.mainPage)return m.mainPage;var d={},a;d.menu=a=m.createMainMenu(t.menu);d.fadeOut=a.fadeOut;d.fadeIn=function(b){a.fadeIn(b);m.currentPage=d};return m.mainPage=d}}).call(Resume);
(function(){var m=this;this.createSubPage=function(t){var d={},a=[],b,c,f,e,h,n=t.placeHolder;if(m.subPage)return m.subPage;d.menu=h=m.createSubMenu(t.menu);e=function(k,g){m.Ajax.get(k,function(i){var p=document.createElement("div");p.style.opacity="0.0";p.innerHTML=i;a[k]=p;g&&g(p)})};d.load=function(k,g,i){if(b=a[k]){d.title=g;i&&i(b)}else e(k,function(p){b=p;d.title=g;i&&i(b)})};c=function(k){var g=1,i;n.appendChild(b);h.itemSelector.disableClick();i=setInterval(function(){b.style.opacity=g*0.0625;
if(g>=16){h.itemSelector.enableClick();clearInterval(i);k&&k()}g++},30)};f=function(k){var g=0,i,p=b;h.itemSelector.disableClick();i=setInterval(function(){p.style.opacity=1-g*0.0625;if(g>=16){h.itemSelector.enableClick();clearInterval(i);n.removeChild(p);k&&k()}g++},30)};d.switchTo=function(k,g,i){m.sync(f,m.partial(d.load,k,g),function(){c(function(){i&&i()})})};d.fadeIn=function(k){m.currentPage=d;h.fadeIn(function(){c(k)})};d.fadeOut=function(k){h.fadeOut(function(){f(k)})};return m.subPage=d}}).call(Resume);
